[package]
name = "repitile_server"
version = "0.1.0"
authors = ["repnop <repnop@outlook.com>"]

[dependencies]
repitile_core = { path = "../repitile_core/" }
gotham = "0.2.0"
hyper = "0.11"
futures = "0.1"
mime = "0.3"
lazy_static = "1.0.0"
dht22_pi = "*"
sysfs_gpio = "0.5.2"